name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libclang-dev libglib2.0-dev libxkbcommon-dev
    - name: Use the latest stable Rust toolchain
      run: rustup update stable && rustup default stable
    - name: Build
      run: cargo build --verbose --features linux
    - name: Run tests
      run: cargo test --verbose --features linux
